
-- EC_01 データベースを作成
drop database if exists EC_01;

create database if not Exists ec_01;
use ec_01;

drop table if exists goods;
drop table if exists customer;
drop table if exists order;
drop table if exists cart;


-- GOODSテーブル作成
CREATE TABLE IF NOT EXISTS GOODS(
GOODS_ID INT(100) AUTO_INCREMENT,
GOODS_NAME VARCHAR(255) NOT NULL,
STOCK INT(100),
PRICE INT(100),
KCAL INT(100)
PRIMARY KEY(GOODS_ID)
);

-- CUSTOMERテーブル作成
CREATE TABLE IF NOT EXISTS CUSTOMER(
ID INT(100) NOT NULL AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(255) NOT NULL,
USER_ID VARCHAR(255) UNIQUE NOT NULL,
PASS VARCHAR(255) NOT NULL,
MAILAD  VARCHAR(255) NOT NULL,
POSTCODE  VARCHAR(7) NOT NULL,
ADDRESS  VARCHAR(255) NOT NULL,
TELNUMBER VARCHAR(12) NOT NULL,
PRIMARY KEY(ID)
);

-- ORDERテーブル作成
CREATE TABLE IF NOT EXISTS ORDER_INFO(
ID INT(100),
GOODS_ID INT(100),
ORDER_COUNT INT(100),
TOTAL_AMOUNT INT(100),
PURCHASEDAY TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
FOREIGN KEY(ID) REFERENCES CUSTOMER(ID),
FOREIGN KEY(GOODS_ID) REFERENCES GOODS(GOODS_ID)
);

-- CARTテーブル作成
CREATE TABLE IF NOT EXISTS CART(
SESSION_ID VARCHAR(255) NOT NULL,
GOODS_NAME VARCHAR(255) NOT NULL,
SALES_NUMBER INT(100) NOT NULL,
PRICE INT(100) NOT NULL,
TOTAL_AMOUNT INT(100) NOT NULL
);



-- GOODSテーブルにデータを3件 挿入
INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE,KCAL)VALUES("チョコプロテイン",10,800,856);
INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE,KCAL)VALUES("イチゴプロテイン",9,900,756);
INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE,KCAL)VALUES("ブドウプロテイン",50,700,656);




-- CUTOMERテーブルにサンプルデータ挿入
INSERT INTO CUSTOMER(CUSTOMER_NAME,USER_ID,PASS,MAILAD,POSTCODE,ADDRESS,TELNUMBER
)VALUES(
"黒柳","totto","madogiwa",totto@gmail.com","1234567","東京都八王子市xxx","09012345678");



-- ORDERテーブルにサンプルデータの挿入
INSERT INTO ORDER(ID,GOODS_ID,ORDER_COUNT,TOTAL_AMOUNT
)VALUES(
1,1,4,12000);


-- CARTテーブルにサンプルデータ挿入
INSERT INTO CART(SESSION_ID,GOODS_NAME,SALES_NUMBERS,PRICE,TOTAL_AMOUNT
)VALUES(
"SESSION_ID","チョコプロテイン",2,800,1600
);

